# Generated by Django 3.0.7 on 2021-08-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='bankid',
            new_name='bank_id',
        ),
    ]
