# Generated by Django 3.0.7 on 2021-08-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20210811_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='email',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
