# Generated by Django 3.0.7 on 2021-08-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_auto_20210815_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='bank_id',
            field=models.IntegerField(unique=True),
        ),
    ]
